# Generated by Django 5.2.7 on 2025-12-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_rename_base_extra_total_transaction_actual_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
