# Generated by Django 5.2.7 on 2025-12-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_transaction_adjustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlineitem',
            name='total_adjustment_amount',
        ),
    ]
