# Generated by Django 5.2.7 on 2025-12-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='Engineer', max_length=20),
        ),
    ]
