# Generated by Django 5.2.7 on 2026-01-05 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_assigned_engineer_job_assigned_operative'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completion_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
