# Generated by Django 5.2.7 on 2026-01-05 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_completion_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='completion_at',
            new_name='completed_at',
        ),
    ]
