# Generated by Django 5.2.7 on 2026-01-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_completion_at_job_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='completed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
