# Generated by Django 5.2.7 on 2026-01-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
