# Generated by Django 5.2.7 on 2025-12-26 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_tenant_email_job_tenant_name_job_tenant_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='assigned_engineer',
            new_name='assigned_operative',
        ),
    ]
