# Generated by Django 5.2.7 on 2025-12-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('in_active', 'In-Active'), ('left', 'Left')], default='Pending', max_length=20),
        ),
    ]
