# Generated by Django 5.2.7 on 2025-12-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('gas_engineer', 'Gas Engineer'), ('plumber', 'Plumber'), ('electrcian', 'Electrician'), ('carpenter', 'Carpenter'), ('handy_person', 'Handy Person')], default='Select Your Job Role', max_length=20),
        ),
    ]
