# Generated by Django 5.2.7 on 2025-12-28 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('jobs', '0003_rename_assigned_engineer_job_assigned_operative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlineitem',
            name='job',
        ),
        migrations.AddField(
            model_name='transaction',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='jobs.job'),
        ),
    ]
