# Generated by Django 5.2.7 on 2025-12-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_transactionlineitem_job_transaction_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='actual_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
