# Generated by Django 5.2.7 on 2025-12-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_transaction_actual_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='actual_cost',
            new_name='base_cost',
        ),
    ]
