# Generated by Django 5.2.7 on 2025-12-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_actual_cost_transaction_base_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlineitem',
            name='total_adjustment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionlineitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
