# Generated by Django 5.2.7 on 2025-12-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_transactionlineitem_total_adjustment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlineitem',
            name='total_adjustment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
