# Generated by Django 5.2.7 on 2025-12-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_transaction_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='base_extra_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
