# Generated by Django 5.2.7 on 2025-12-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_transaction_base_extra_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='base_extra_total',
            new_name='actual_cost',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='extras',
        ),
    ]
