# Generated by Django 5.2.7 on 2025-12-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_remove_transactionlineitem_total_adjustment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
