# Generated by Django 5.2.7 on 2026-01-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_transaction_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
