# Generated by Django 5.2.7 on 2026-01-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_transaction_cancelled_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
    ]
