# Generated by Django 5.2.7 on 2026-01-05 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_remove_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='paid_at',
        ),
    ]
